logging:
  level:
    org:
      springframework: ERROR 
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:file:C:/data/planetdb;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE '
  profiles:
    active: dev 
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
